-- Create a new database
CREATE DATABASE imdb;

-- Switch to the new database for subsequent SQL commands
USE imdb;


CREATE TABLE mytable(
   director_name             VARCHAR(18) NOT NULL 
  ,duration                  INTEGER 
  ,director_facebook_likes   INTEGER  NOT NULL
  ,actor_3_facebook_likes    INTEGER 
  ,actor_2_name              VARCHAR(20) NOT NULL
  ,actor_1_facebook_likes    INTEGER  NOT NULL
  ,gross                     INTEGER 
  ,genres                    VARCHAR(57) NOT NULL
  ,actor_1_name              VARCHAR(20) NOT NULL
  ,movie_title               VARCHAR(55) NOT NULL
  ,cast_total_facebook_likes INTEGER  NOT NULL
  ,actor_3_name              VARCHAR(20)
  ,plot_keywords             VARCHAR(95)
  ,country                   VARCHAR(11)
  ,content_rating            VARCHAR(5)
  ,budget                    INTEGER 
  ,title_year                INTEGER 
  ,actor_2_facebook_likes    INTEGER  NOT NULL
  ,imdb_score                NUMERIC(3,1) NOT NULL
  ,movie_facebook_likes      INTEGER  NOT NULL
);
INSERT INTO mytable(director_name,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,actor_1_name,movie_title,cast_total_facebook_likes,actor_3_name,plot_keywords,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,movie_facebook_likes) VALUES ('James Cameron',178,0,855,'Joel David Moore',1000,760505847,'Action|Adventure|Fantasy|Sci-Fi','CCH Pounder','Avatar',4834,'Wes Studi','avatar|future|marine|native|paraplegic','USA','PG-13',237000000,2009,936,7.9,33000);
INSERT INTO mytable(director_name,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,actor_1_name,movie_title,cast_total_facebook_likes,actor_3_name,plot_keywords,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,movie_facebook_likes) VALUES ('Gore Verbinski',169,563,1000,'Orlando Bloom',40000,309404152,'Action|Adventure|Fantasy','Johnny Depp','Pirates of the Caribbean: At World''s End',48350,'Jack Davenport','goddess|marriage ceremony|marriage proposal|pirate|singapore','USA','PG-13',300000000,2007,5000,7.1,0);
INSERT INTO mytable(director_name,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,actor_1_name,movie_title,cast_total_facebook_likes,actor_3_name,plot_keywords,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,movie_facebook_likes) VALUES ('Sam Mendes',148,0,161,'Rory Kinnear',11000,200074175,'Action|Adventure|Thriller','Christoph Waltz','Spectre',11700,'Stephanie Sigman','bomb|espionage|sequel|spy|terrorist','UK','PG-13',245000000,2015,393,6.8,85000);
INSERT INTO mytable(director_name,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,actor_1_name,movie_title,cast_total_facebook_likes,actor_3_name,plot_keywords,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,movie_facebook_likes) VALUES ('Christopher Nolan',164,22000,23000,'Christian Bale',27000,448130642,'Action|Thriller','Tom Hardy','The Dark Knight Rises',106759,'Joseph Gordon-Levitt','deception|imprisonment|lawlessness|police officer|terrorist plot','USA','PG-13',250000000,2012,23000,8.5,164000);
INSERT INTO mytable(director_name,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,actor_1_name,movie_title,cast_total_facebook_likes,actor_3_name,plot_keywords,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,movie_facebook_likes) VALUES ('Doug Walker',NULL,131,NULL,'Rob Walker',131,NULL,'Documentary','Doug Walker','Star Wars: Episode VII - The Force Awakens',143,NULL,NULL,NULL,NULL,NULL,NULL,12,7.1,0);
INSERT INTO mytable(director_name,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,actor_1_name,movie_title,cast_total_facebook_likes,actor_3_name,plot_keywords,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,movie_facebook_likes) VALUES ('Andrew Stanton',132,475,530,'Samantha Morton',640,73058679,'Action|Adventure|Sci-Fi','Daryl Sabara','John Carter',1873,'Polly Walker','alien|american civil war|male nipple|mars|princess','USA','PG-13',263700000,2012,632,6.6,24000);
INSERT INTO mytable(director_name,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,actor_1_name,movie_title,cast_total_facebook_likes,actor_3_name,plot_keywords,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,movie_facebook_likes) VALUES ('Sam Raimi',156,0,4000,'James Franco',24000,336530303,'Action|Adventure|Romance','J.K. Simmons','Spider-Man 3',46055,'Kirsten Dunst','sandman|spider man|symbiote|venom|villain','USA','PG-13',258000000,2007,11000,6.2,0);
INSERT INTO mytable(director_name,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,actor_1_name,movie_title,cast_total_facebook_likes,actor_3_name,plot_keywords,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,movie_facebook_likes) VALUES ('Nathan Greno',100,15,284,'Donna Murphy',799,200807262,'Adventure|Animation|Comedy|Family|Fantasy|Musical|Romance','Brad Garrett','Tangled',2036,'M.C. Gainey','17th century|based on fairy tale|disney|flower|tower','USA','PG',260000000,2010,553,7.8,29000);
INSERT INTO mytable(director_name,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,actor_1_name,movie_title,cast_total_facebook_likes,actor_3_name,plot_keywords,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,movie_facebook_likes) VALUES ('Joss Whedon',141,0,19000,'Robert Downey Jr.',26000,458991599,'Action|Adventure|Sci-Fi','Chris Hemsworth','Avengers: Age of Ultron',92000,'Scarlett Johansson','artificial intelligence|based on comic book|captain america|marvel cinematic universe|superhero','USA','PG-13',250000000,2015,21000,7.5,118000);
INSERT INTO mytable(director_name,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,actor_1_name,movie_title,cast_total_facebook_likes,actor_3_name,plot_keywords,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,movie_facebook_likes) VALUES ('David Yates',153,282,10000,'Daniel Radcliffe',25000,301956980,'Adventure|Family|Fantasy|Mystery','Alan Rickman','Harry Potter and the Half-Blood Prince',58753,'Rupert Grint','blood|book|love|potion|professor','UK','PG',250000000,2009,11000,7.5,10000);
INSERT INTO mytable(director_name,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,actor_1_name,movie_title,cast_total_facebook_likes,actor_3_name,plot_keywords,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,movie_facebook_likes) VALUES ('Zack Snyder',183,0,2000,'Lauren Cohan',15000,330249062,'Action|Adventure|Sci-Fi','Henry Cavill','Batman v Superman: Dawn of Justice',24450,'Alan D. Purwin','based on comic book|batman|sequel to a reboot|superhero|superman','USA','PG-13',250000000,2016,4000,6.9,197000);
INSERT INTO mytable(director_name,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,actor_1_name,movie_title,cast_total_facebook_likes,actor_3_name,plot_keywords,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,movie_facebook_likes) VALUES ('Bryan Singer',169,0,903,'Marlon Brando',18000,200069408,'Action|Adventure|Sci-Fi','Kevin Spacey','Superman Returns',29991,'Frank Langella','crystal|epic|lex luthor|lois lane|return to earth','USA','PG-13',209000000,2006,10000,6.1,0);
INSERT INTO mytable(director_name,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,actor_1_name,movie_title,cast_total_facebook_likes,actor_3_name,plot_keywords,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,movie_facebook_likes) VALUES ('Marc Forster',106,395,393,'Mathieu Amalric',451,168368427,'Action|Adventure','Giancarlo Giannini','Quantum of Solace',2023,'Rory Kinnear','action hero|attempted rape|bond girl|official james bond series|revenge','UK','PG-13',200000000,2008,412,6.7,0);
INSERT INTO mytable(director_name,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,actor_1_name,movie_title,cast_total_facebook_likes,actor_3_name,plot_keywords,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,movie_facebook_likes) VALUES ('Gore Verbinski',151,563,1000,'Orlando Bloom',40000,423032628,'Action|Adventure|Fantasy','Johnny Depp','Pirates of the Caribbean: Dead Man''s Chest',48486,'Jack Davenport','box office hit|giant squid|heart|liar''s dice|monster','USA','PG-13',225000000,2006,5000,7.3,5000);
INSERT INTO mytable(director_name,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,actor_1_name,movie_title,cast_total_facebook_likes,actor_3_name,plot_keywords,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,movie_facebook_likes) VALUES ('Gore Verbinski',150,563,1000,'Ruth Wilson',40000,89289910,'Action|Adventure|Western','Johnny Depp','The Lone Ranger',45757,'Tom Wilkinson','horse|outlaw|texas|texas ranger|train','USA','PG-13',215000000,2013,2000,6.5,48000);
INSERT INTO mytable(director_name,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,actor_1_name,movie_title,cast_total_facebook_likes,actor_3_name,plot_keywords,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,movie_facebook_likes) VALUES ('Zack Snyder',143,0,748,'Christopher Meloni',15000,291021565,'Action|Adventure|Fantasy|Sci-Fi','Henry Cavill','Man of Steel',20495,'Harry Lennix','based on comic book|british actor playing american character|final battle|origin of hero|reboot','USA','PG-13',225000000,2013,3000,7.2,118000);
INSERT INTO mytable(director_name,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,actor_1_name,movie_title,cast_total_facebook_likes,actor_3_name,plot_keywords,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,movie_facebook_likes) VALUES ('Andrew Adamson',150,80,201,'Pierfrancesco Favino',22000,141614023,'Action|Adventure|Family|Fantasy','Peter Dinklage','The Chronicles of Narnia: Prince Caspian',22697,'Damizar','brother brother relationship|brother sister relationship|good versus evil|king|narnia','USA','PG',225000000,2008,216,6.6,0);
INSERT INTO mytable(director_name,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,actor_1_name,movie_title,cast_total_facebook_likes,actor_3_name,plot_keywords,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,movie_facebook_likes) VALUES ('Joss Whedon',173,0,19000,'Robert Downey Jr.',26000,623279547,'Action|Adventure|Sci-Fi','Chris Hemsworth','The Avengers',87697,'Scarlett Johansson','alien invasion|assassin|battle|iron man|soldier','USA','PG-13',220000000,2012,21000,8.1,123000);
INSERT INTO mytable(director_name,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,actor_1_name,movie_title,cast_total_facebook_likes,actor_3_name,plot_keywords,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,movie_facebook_likes) VALUES ('Rob Marshall',136,252,1000,'Sam Claflin',40000,241063875,'Action|Adventure|Fantasy','Johnny Depp','Pirates of the Caribbean: On Stranger Tides',54083,'Stephen Graham','blackbeard|captain|pirate|revenge|soldier','USA','PG-13',250000000,2011,11000,6.7,58000);
INSERT INTO mytable(director_name,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,actor_1_name,movie_title,cast_total_facebook_likes,actor_3_name,plot_keywords,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,movie_facebook_likes) VALUES ('Barry Sonnenfeld',106,188,718,'Michael Stuhlbarg',10000,179020854,'Action|Adventure|Comedy|Family|Fantasy|Sci-Fi','Will Smith','Men in Black 3',12572,'Nicole Scherzinger','alien|criminal|m.i.b.|maximum security prison|prison','USA','PG-13',225000000,2012,816,6.8,40000);
INSERT INTO mytable(director_name,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,actor_1_name,movie_title,cast_total_facebook_likes,actor_3_name,plot_keywords,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,movie_facebook_likes) VALUES ('Peter Jackson',164,0,773,'Adam Brown',5000,255108370,'Adventure|Fantasy','Aidan Turner','The Hobbit: The Battle of the Five Armies',9152,'James Nesbitt','army|elf|hobbit|middle earth|orc','New Zealand','PG-13',250000000,2014,972,7.5,65000);
INSERT INTO mytable(director_name,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,actor_1_name,movie_title,cast_total_facebook_likes,actor_3_name,plot_keywords,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,movie_facebook_likes) VALUES ('Marc Webb',153,464,963,'Andrew Garfield',15000,262030663,'Action|Adventure|Fantasy','Emma Stone','The Amazing Spider-Man',28489,'Chris Zylka','lizard|outcast|spider|spider man|teenager','USA','PG-13',230000000,2012,10000,7,56000);
INSERT INTO mytable(director_name,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,actor_1_name,movie_title,cast_total_facebook_likes,actor_3_name,plot_keywords,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,movie_facebook_likes) VALUES ('Ridley Scott',156,0,738,'William Hurt',891,105219735,'Action|Adventure|Drama|History','Mark Addy','Robin Hood',3244,'Scott Grimes','1190s|archer|england|king of england|robin hood','USA','PG-13',200000000,2010,882,6.7,17000);
INSERT INTO mytable(director_name,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,actor_1_name,movie_title,cast_total_facebook_likes,actor_3_name,plot_keywords,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,movie_facebook_likes) VALUES ('Peter Jackson',186,0,773,'Adam Brown',5000,258355354,'Adventure|Fantasy','Aidan Turner','The Hobbit: The Desolation of Smaug',9152,'James Nesbitt','dwarf|elf|lake town|mountain|sword and sorcery','USA','PG-13',225000000,2013,972,7.9,83000);
INSERT INTO mytable(director_name,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,actor_1_name,movie_title,cast_total_facebook_likes,actor_3_name,plot_keywords,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,movie_facebook_likes) VALUES ('Chris Weitz',113,129,1000,'Eva Green',16000,70083519,'Adventure|Family|Fantasy','Christopher Lee','The Golden Compass',24106,'Kristin Scott Thomas','children|epic|friend|girl|quest','USA','PG-13',180000000,2007,6000,6.1,0);
INSERT INTO mytable(director_name,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,actor_1_name,movie_title,cast_total_facebook_likes,actor_3_name,plot_keywords,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,movie_facebook_likes) VALUES ('Peter Jackson',201,0,84,'Thomas Kretschmann',6000,218051260,'Action|Adventure|Drama|Romance','Naomi Watts','King Kong',7123,'Evan Parke','animal name in title|ape abducts a woman|gorilla|island|king kong','New Zealand','PG-13',207000000,2005,919,7.2,0);
INSERT INTO mytable(director_name,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,actor_1_name,movie_title,cast_total_facebook_likes,actor_3_name,plot_keywords,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,movie_facebook_likes) VALUES ('James Cameron',194,0,794,'Kate Winslet',29000,658672302,'Drama|Romance','Leonardo DiCaprio','Titanic',45223,'Gloria Stuart','artist|love|ship|titanic|wet','USA','PG-13',200000000,1997,14000,7.7,26000);
INSERT INTO mytable(director_name,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,actor_1_name,movie_title,cast_total_facebook_likes,actor_3_name,plot_keywords,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,movie_facebook_likes) VALUES ('Anthony Russo',147,94,11000,'Scarlett Johansson',21000,407197282,'Action|Adventure|Sci-Fi','Robert Downey Jr.','Captain America: Civil War',64798,'Chris Evans','based on comic book|knife|marvel cinematic universe|returning character killed off|superhero','USA','PG-13',250000000,2016,19000,8.2,72000);

INSERT INTO mytable(director_name,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,actor_1_name,movie_title,cast_total_facebook_likes,actor_3_name,plot_keywords,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,movie_facebook_likes) VALUES ('Colin Trevorrow',124,365,1000,'Judy Greer',3000,652177271,'Action|Adventure|Sci-Fi|Thriller','Bryce Dallas Howard','Jurassic World',8458,'Omar Sy','dinosaur|disaster film|experiment gone wrong|jurassic park|velociraptor','USA','PG-13',150000000,2015,2000,7,150000);
INSERT INTO mytable(director_name,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,actor_1_name,movie_title,cast_total_facebook_likes,actor_3_name,plot_keywords,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,movie_facebook_likes) VALUES ('Sam Mendes',143,0,393,'Helen McCrory',883,304360277,'Action|Adventure|Thriller','Albert Finney','Skyfall',2039,'Rory Kinnear','brawl|childhood home|computer cracker|intelligence agency|terrorist cell','UK','PG-13',200000000,2012,563,7.8,80000);
INSERT INTO mytable(director_name,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,actor_1_name,movie_title,cast_total_facebook_likes,actor_3_name,plot_keywords,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,movie_facebook_likes) VALUES ('Sam Raimi',135,0,4000,'James Franco',24000,373377893,'Action|Adventure|Fantasy|Romance','J.K. Simmons','Spider-Man 2',43388,'Kirsten Dunst','death|doctor|scientist|super villain|tentacle','USA','PG-13',200000000,2004,11000,7.3,0);
INSERT INTO mytable(director_name,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,actor_1_name,movie_title,cast_total_facebook_likes,actor_3_name,plot_keywords,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,movie_facebook_likes) VALUES ('Shane Black',195,1000,3000,'Jon Favreau',21000,408992272,'Action|Adventure|Sci-Fi','Robert Downey Jr.','Iron Man 3',30426,'Don Cheadle','armor|explosion|human bomb|missile attack|terrorist','USA','PG-13',200000000,2013,4000,7.2,95000);
INSERT INTO mytable(director_name,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,actor_1_name,movie_title,cast_total_facebook_likes,actor_3_name,plot_keywords,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,movie_facebook_likes) VALUES ('Tim Burton',108,13000,11000,'Alan Rickman',40000,334185206,'Adventure|Family|Fantasy','Johnny Depp','Alice in Wonderland',79957,'Anne Hathaway','alice in wonderland|mistaking reality for dream|queen|shrinking|shrinking potion','USA','PG',200000000,2010,25000,6.5,24000);
INSERT INTO mytable(director_name,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,actor_1_name,movie_title,cast_total_facebook_likes,actor_3_name,plot_keywords,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,movie_facebook_likes) VALUES ('Brett Ratner',104,420,560,'Kelsey Grammer',20000,234360014,'Action|Adventure|Fantasy|Sci-Fi|Thriller','Hugh Jackman','X-Men: The Last Stand',21714,'Daniel Cudmore','battle|mutant|outrage|walking through a wall|x men','Canada','PG-13',210000000,2006,808,6.8,0);
INSERT INTO mytable(director_name,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,actor_1_name,movie_title,cast_total_facebook_likes,actor_3_name,plot_keywords,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,movie_facebook_likes) VALUES ('Dan Scanlon',104,37,760,'Tyler Labine',12000,268488329,'Adventure|Animation|Comedy|Family|Fantasy','Steve Buscemi','Monsters University',14863,'Sean Hayes','cheating|fraternity|monster|singing in a car|university','USA','G',200000000,2013,779,7.3,44000);
INSERT INTO mytable(director_name,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,actor_1_name,movie_title,cast_total_facebook_likes,actor_3_name,plot_keywords,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,movie_facebook_likes) VALUES ('Michael Bay',150,0,464,'Kevin Dunn',894,402076689,'Action|Adventure|Sci-Fi','Glenn Morshower','Transformers: Revenge of the Fallen',3218,'Ramon Rodriguez','autobot|decepticon|machine|sun|symbol','USA','PG-13',200000000,2009,581,6,0);
INSERT INTO mytable(director_name,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,actor_1_name,movie_title,cast_total_facebook_likes,actor_3_name,plot_keywords,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,movie_facebook_likes) VALUES ('Michael Bay',165,0,808,'Sophia Myles',974,245428137,'Action|Adventure|Sci-Fi','Bingbing Li','Transformers: Age of Extinction',3988,'Kelsey Grammer','blockbuster|bumblebee the character|semi truck and trailer|texas|truck','USA','PG-13',210000000,2014,956,5.7,56000);
INSERT INTO mytable(director_name,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,actor_1_name,movie_title,cast_total_facebook_likes,actor_3_name,plot_keywords,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,movie_facebook_likes) VALUES ('Sam Raimi',130,0,11000,'Mila Kunis',44000,234903076,'Adventure|Family|Fantasy','Tim Holmes','Oz the Great and Powerful',73441,'James Franco','circus|magic|magician|oz|witch','USA','PG',215000000,2013,15000,6.4,60000);
INSERT INTO mytable(director_name,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,actor_1_name,movie_title,cast_total_facebook_likes,actor_3_name,plot_keywords,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,movie_facebook_likes) VALUES ('Marc Webb',142,464,825,'Andrew Garfield',15000,202853933,'Action|Adventure|Fantasy|Sci-Fi','Emma Stone','The Amazing Spider-Man 2',28631,'B.J. Novak','costumed hero|death of girlfriend|masked vigilante|returning character killed off|teenager','USA','PG-13',200000000,2014,10000,6.7,41000);
INSERT INTO mytable(director_name,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,actor_1_name,movie_title,cast_total_facebook_likes,actor_3_name,plot_keywords,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,movie_facebook_likes) VALUES ('Joseph Kosinski',125,364,1000,'Olivia Wilde',12000,172051787,'Action|Adventure|Sci-Fi','Jeff Bridges','TRON: Legacy',25550,'James Frain','arcade|bridge|disappearance|escape|warrior','USA','PG',170000000,2010,10000,6.8,30000);
INSERT INTO mytable(director_name,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,actor_1_name,movie_title,cast_total_facebook_likes,actor_3_name,plot_keywords,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,movie_facebook_likes) VALUES ('John Lasseter',106,487,776,'Thomas Kretschmann',1000,191450875,'Adventure|Animation|Comedy|Family|Sport','Joe Mantegna','Cars 2',4482,'Eddie Izzard','best friend|car race|conspiracy|gadget car|spy','USA','G',200000000,2011,919,6.3,10000);
INSERT INTO mytable(director_name,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,actor_1_name,movie_title,cast_total_facebook_likes,actor_3_name,plot_keywords,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,movie_facebook_likes) VALUES ('Martin Campbell',123,258,326,'Temuera Morrison',16000,116593191,'Action|Adventure|Sci-Fi','Ryan Reynolds','Green Lantern',17657,'Taika Waititi','autopsy|lantern|planet|ring|test pilot','USA','PG-13',200000000,2011,368,5.6,24000);
INSERT INTO mytable(director_name,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,actor_1_name,movie_title,cast_total_facebook_likes,actor_3_name,plot_keywords,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,movie_facebook_likes) VALUES ('Lee Unkrich',103,125,721,'John Ratzenberger',15000,414984497,'Adventure|Animation|Comedy|Family|Fantasy','Tom Hanks','Toy Story 3',19085,'Don Rickles','college|day care|escape|teddy bear|toy','USA','G',200000000,2010,1000,8.3,30000);
INSERT INTO mytable(director_name,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,actor_1_name,movie_title,cast_total_facebook_likes,actor_3_name,plot_keywords,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,movie_facebook_likes) VALUES ('McG',118,368,988,'Bryce Dallas Howard',23000,125320003,'Action|Adventure|Sci-Fi','Christian Bale','Terminator Salvation',27468,'Common','death row|future|machine|rescue|skynet','USA','PG-13',200000000,2009,3000,6.6,0);
INSERT INTO mytable(director_name,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,actor_1_name,movie_title,cast_total_facebook_likes,actor_3_name,plot_keywords,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,movie_facebook_likes) VALUES ('James Wan',140,0,14000,'Paul Walker',26000,350034110,'Action|Crime|Thriller','Jason Statham','Furious 7',79150,'Vin Diesel','car falling off a cliff|hospital|revenge|star died before release|terrorist','USA','PG-13',190000000,2015,23000,7.2,94000);
INSERT INTO mytable(director_name,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,actor_1_name,movie_title,cast_total_facebook_likes,actor_3_name,plot_keywords,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,movie_facebook_likes) VALUES ('Marc Forster',123,395,1000,'Brad Pitt',17000,202351611,'Action|Adventure|Horror|Sci-Fi|Thriller','Peter Capaldi','World War Z',32392,'Mireille Enos','chaos|disease|infection|pandemic|zombie','USA','PG-13',190000000,2013,11000,7,129000);
INSERT INTO mytable(director_name,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,actor_1_name,movie_title,cast_total_facebook_likes,actor_3_name,plot_keywords,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,movie_facebook_likes) VALUES ('Bryan Singer',149,0,20000,'Peter Dinklage',34000,233914986,'Action|Adventure|Fantasy|Sci-Fi|Thriller','Jennifer Lawrence','X-Men: Days of Future Past',91434,'Hugh Jackman','dystopia|super strength|supernatural power|time paradox|time travel','USA','PG-13',200000000,2014,22000,8,82000);
INSERT INTO mytable(director_name,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,actor_1_name,movie_title,cast_total_facebook_likes,actor_3_name,plot_keywords,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,movie_facebook_likes) VALUES ('J.J. Abrams',132,14000,928,'Bruce Greenwood',19000,228756232,'Action|Adventure|Sci-Fi','Benedict Cumberbatch','Star Trek Into Darkness',21411,'Noel Clarke','admiral|captain|manhunt|mission|space','USA','PG-13',190000000,2013,981,7.8,92000);
INSERT INTO mytable(director_name,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,actor_1_name,movie_title,cast_total_facebook_likes,actor_3_name,plot_keywords,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,movie_facebook_likes) VALUES ('Bryan Singer',114,0,140,'Ewen Bremner',979,65171860,'Adventure|Fantasy','Eddie Marsan','Jack the Giant Slayer',1766,'Ralph Brown','bean|giant|king|no opening credits|princess','USA','PG-13',195000000,2013,557,6.3,22000);
INSERT INTO mytable(director_name,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,actor_1_name,movie_title,cast_total_facebook_likes,actor_3_name,plot_keywords,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,movie_facebook_likes) VALUES ('Baz Luhrmann',143,1000,77,'Elizabeth Debicki',29000,144812796,'Drama|Romance','Leonardo DiCaprio','The Great Gatsby',29770,'Steve Bisley','ingratitude|mansion|party|title appears in writing|tragedy','Australia','PG-13',105000000,2013,509,7.3,115000);
INSERT INTO mytable(director_name,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,actor_1_name,movie_title,cast_total_facebook_likes,actor_3_name,plot_keywords,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,movie_facebook_likes) VALUES ('Mike Newell',116,179,236,'Richard Coyle',15000,90755643,'Action|Adventure|Fantasy|Romance','Jake Gyllenhaal','Prince of Persia: The Sands of Time',16149,'Reece Ritchie','alamut|dagger|king|persia|princess','USA','PG-13',200000000,2010,567,6.6,23000);
INSERT INTO mytable(director_name,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,actor_1_name,movie_title,cast_total_facebook_likes,actor_3_name,plot_keywords,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,movie_facebook_likes) VALUES ('Guillermo del Toro',131,0,919,'Clifton Collins Jr.',16000,101785482,'Action|Adventure|Sci-Fi','Charlie Hunnam','Pacific Rim',19166,'Larry Joe Campbell','giant monster|kaiju|pilot|portal|robot','USA','PG-13',190000000,2013,968,7,83000);
INSERT INTO mytable(director_name,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,actor_1_name,movie_title,cast_total_facebook_likes,actor_3_name,plot_keywords,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,movie_facebook_likes) VALUES ('Michael Bay',154,0,581,'Lester Speight',894,352358779,'Action|Adventure|Sci-Fi','Glenn Morshower','Transformers: Dark of the Moon',2593,'Kevin Dunn','autobot|decepticon|job interview|moon|spacecraft','USA','PG-13',195000000,2011,829,6.3,46000);
INSERT INTO mytable(director_name,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,actor_1_name,movie_title,cast_total_facebook_likes,actor_3_name,plot_keywords,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,movie_facebook_likes) VALUES ('Steven Spielberg',122,14000,1000,'Ray Winstone',11000,317011114,'Action|Adventure|Fantasy','Harrison Ford','Indiana Jones and the Kingdom of the Crystal Skull',14959,'Jim Broadbent','cult figure|femme fatale|indiana jones|unsubtitled foreign language|year 1957','USA','PG-13',185000000,2008,1000,6.2,5000);
INSERT INTO mytable(director_name,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,actor_1_name,movie_title,cast_total_facebook_likes,actor_3_name,plot_keywords,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,movie_facebook_likes) VALUES ('Peter Sohn',93,113,113,'Jack McGraw',275,123070338,'Adventure|Animation|Comedy|Family|Fantasy','A.J. Buckley','The Good Dinosaur',696,'Peter Sohn','apatosaurus|asteroid|dinosaur|fear|river','USA','PG',NULL,2015,150,6.8,20000);
INSERT INTO mytable(director_name,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,actor_1_name,movie_title,cast_total_facebook_likes,actor_3_name,plot_keywords,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,movie_facebook_likes) VALUES ('Mark Andrews',93,56,838,'John Ratzenberger',2000,237282182,'Adventure|Animation|Comedy|Family|Fantasy','Kelly Macdonald','Brave',5005,'Julie Walters','archery|coming of age|female warrior|princess|rebellious daughter','USA','PG',185000000,2012,1000,7.2,39000);
INSERT INTO mytable(director_name,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,actor_1_name,movie_title,cast_total_facebook_likes,actor_3_name,plot_keywords,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,movie_facebook_likes) VALUES ('Justin Lin',122,681,105,'Melissa Roxburgh',998,130468626,'Action|Adventure|Sci-Fi|Thriller','Sofia Boutella','Star Trek Beyond',1327,'Lydia Wilson','hatred|sequel|space opera|star trek|third part','USA','PG-13',185000000,2016,119,7.5,30000);
INSERT INTO mytable(director_name,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,actor_1_name,movie_title,cast_total_facebook_likes,actor_3_name,plot_keywords,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,movie_facebook_likes) VALUES ('Andrew Stanton',98,475,522,'Fred Willard',1000,223806889,'Adventure|Animation|Family|Sci-Fi','John Ratzenberger','WALLÃ‚Â·E',2975,'Jeff Garlin','earth|obesity|plant|robot|soil','USA','G',180000000,2008,729,8.4,16000);
INSERT INTO mytable(director_name,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,actor_1_name,movie_title,cast_total_facebook_likes,actor_3_name,plot_keywords,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,movie_facebook_likes) VALUES ('Brett Ratner',91,420,173,'Dana Ivey',268,140080850,'Action|Comedy|Crime|Thriller','Tzi Ma','Rush Hour 3',1125,'NoÃƒÂ©mie Lenoir','ambassador|assassination|chinese|french|triad','USA','PG-13',140000000,2007,268,6.2,0);
INSERT INTO mytable(director_name,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,actor_1_name,movie_title,cast_total_facebook_likes,actor_3_name,plot_keywords,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,movie_facebook_likes) VALUES ('Roland Emmerich',158,776,310,'Liam James',1000,166112167,'Action|Adventure|Sci-Fi','Oliver Platt','2012',2144,'Tom McCarthy','ark|catastrophe|geologist|president|writer','USA','PG-13',200000000,2009,468,5.8,13000);
INSERT INTO mytable(director_name,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,actor_1_name,movie_title,cast_total_facebook_likes,actor_3_name,plot_keywords,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,movie_facebook_likes) VALUES ('Robert Zemeckis',96,0,10000,'Colin Firth',18000,137850096,'Animation|Drama|Family|Fantasy','Robin Wright','A Christmas Carol',48878,'Gary Oldman','charles dickens|christmas|christmas eve|ghost|scrooge','USA','PG',200000000,2009,14000,6.8,0);
INSERT INTO mytable(director_name,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,actor_1_name,movie_title,cast_total_facebook_likes,actor_3_name,plot_keywords,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,movie_facebook_likes) VALUES ('Lana Wachowski',127,0,13000,'Mila Kunis',17000,47375327,'Action|Adventure|Sci-Fi','Channing Tatum','Jupiter Ascending',47334,'Eddie Redmayne','box office flop|critically bashed|planet earth|space opera|woman in bra and panties','USA','PG-13',176000000,2015,15000,5.4,44000);
